masterschedule/urls.py
from django.shortcuts import redirect
from django.conf.urls import patterns, include, url
from django.contrib import admin
from vanilla import TemplateView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/profile/$', lambda *args: redirect("conferences")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^support/$', TemplateView.as_view(template_name="support.html"), name='support'),
    url(r'', include('schedule.urls')),
)

schedule/urls.py
from django.conf.urls import patterns, include, url

from schedule.views import (
        # Public
        ConferenceCreate, ConferenceList, MasterSchedule, PersonalSchedule,
        RoomSchedule, PrintAll, AirportDesires,
        
        # Permission required
        PersonCrud, VenueCrud, RoleTypeCrud, EventAssigner, ConferenceUpdate, edit_event,

        # Secret URL
        AvailabilitySurvey,

        # Ajax
        EventRoleAjaxCrud, update_event_attribute,
        # Ajax: permission required
        get_available_people, get_available_venues, get_admin_data
    )

urlpatterns = patterns('',
    # AJAX methods for altering events.
    url(r'^event/edit-role/', EventRoleAjaxCrud.as_view(), name='event_role_crud'),
    url(r'^event/available-people/', get_available_people, name='get_available_people'),
    url(r'^event/update-event-attribute/', update_event_attribute, name='update_event_attribute'),

    #
    url(r'^event/available-venues/', get_available_venues, name='get_available_venues'),
    url(r'^$', ConferenceList.as_view(), name='conferences'),
    url(r'^admin-data$', get_admin_data, name='get_admin_data'),
    url(r'^schedule/(?P<slug>[^/]+)/$', MasterSchedule.as_view(), name='master_schedule'),
    url(r'^event/(?P<slug>[^/]+)/$', edit_event, name='edit_event'),
    url(r'^assign/(?P<slug>[^/]+)/$', EventAssigner.as_view(), name='event_assigner'),
    url(r'^venues/(?P<slug>[^/]+)/$', VenueCrud.as_view(), name='venue_crud'),
    url(r'^people/(?P<slug>[^/]+)/$', PersonCrud.as_view(), name='person_crud'),
    url(r'^roletypes/(?P<slug>[^/]+)/$', RoleTypeCrud.as_view(), name='roletype_crud'),
    url(r'^airport/(?P<slug>[^/]+)/$', AirportDesires.as_view(), name='airport_list'),
    url(r'^printall/(?P<slug>[^/]+)/$', PrintAll.as_view(), name='print_all'),
    url(r'^survey/(?P<slug>[^/]+)/$', AvailabilitySurvey.as_view(), name='availability_survey'),
    url(r'^personal/(?P<slug>[^/]+)/(?P<pk>\d+)/$', PersonalSchedule.as_view(), name='personal_schedule'),
    url(r'^room/(?P<slug>[^/]+)/$', RoomSchedule.as_view(), name='venue_schedule'),
    url(r'^create-conference/', ConferenceCreate.as_view(), name='conference_create'),
    url(r'^update-conference/(?P<slug>[^/]+)/$', ConferenceUpdate.as_view(),
        name='conference_update'),
)

schedule/models.py
import os
import base64
import uuid

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

def random_slug():
    return base64.urlsafe_b64encode(os.urandom(32))

class RandomSlugModel(models.Model):
    random_slug = models.CharField(max_length=64, editable=False, unique=True)

    def save(self, *args, **kwargs):
        if not self.random_slug:
            self.random_slug = random_slug()
        super(RandomSlugModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True

class ConferenceManager(models.Manager):
    def public_for(self, user):
        q = Q(public=True)
        if user.is_authenticated():
            q = q | Q(admins__id=user.id)
        return self.active().filter(q).order_by('-created').distinct()

    def editable_by(self, user):
        return Conference.objects.filter(admins__id=user.id)

    def active(self):
        return self.filter(archived=False)

class ProspectiveAdmin(models.Model):
    email = models.EmailField(max_length=255, unique=True)
    def __unicode__(self):
        return self.email

@receiver(post_save)
def convert_prospective_admins(sender, instance, created, raw, *args, **kwargs):
    if created and not raw and isinstance(instance, User) and instance.email:
        user = instance
        try:
            prospy = ProspectiveAdmin.objects.get(email=user.email)
        except ProspectiveAdmin.DoesNotExist:
            return
        for conference in prospy.conference_set.all():
            conference.admins.add(user)
            conference.prospective_admins.remove(prospy)
        prospy.delete()

class Conference(RandomSlugModel):
    name = models.CharField(max_length=70)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    public = models.BooleanField(default=True,
            help_text="List this conference on the front page? Uncheck for more privacy.")
    archived = models.BooleanField(default=False,
            help_text="Remove this conference from your list?")
    admins = models.ManyToManyField(User)
    prospective_admins = models.ManyToManyField(ProspectiveAdmin, null=True, blank=True)

    objects = ConferenceManager()

    def is_admin(self, user):
        return (user.is_superuser or self.admins.filter(pk=user.pk).exists())

    def get_absolute_url(self):
        return reverse("master_schedule", kwargs={"slug": self.random_slug})

    def __unicode__(self):
        return self.name

class Person(RandomSlugModel):
    conference = models.ForeignKey(Conference)
    name = models.CharField(max_length=70)
    attending = models.BooleanField(default=True,
            help_text="Are you attending?")
    availability_start_date = models.DateTimeField(blank=True, null=True,
            help_text="When are you first available to volunteer?")
    availability_end_date = models.DateTimeField(blank=True, null=True,
            help_text="When do you leave?")
    want_airport_pickup = models.BooleanField(default=False,
            help_text="Airport pickups might not be available.  But if we have capacity, would you like to get a ride?")
    airport_pickup_date = models.DateTimeField(blank=True, null=True,
            help_text="When do you arrive at the airport?")
    airport_pickup_details = models.TextField(blank=True,
            help_text="Please list your flight information.")
    want_airport_dropoff = models.BooleanField(default=False,
            help_text="Airport dropoffs might not be available.  But if we have capacity, would you like to get a ride?")
    airport_dropoff_date = models.DateTimeField(blank=True, null=True,
            help_text="When do you need to be at the airport? (e.g. one hour before flight departure)")
    airport_dropoff_details = models.TextField(blank=True,
            help_text="Please list your flight information.")

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class OtherCommitment(models.Model):
    person = models.ForeignKey(Person)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __unicode__(self):
        return unicode(self.person)

class Period(models.Model):
    conference = models.ForeignKey(Conference)
    period = models.CharField(max_length=70)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __unicode__(self):
        return self.period

class Venue(RandomSlugModel):
    conference = models.ForeignKey(Conference)
    name = models.CharField(max_length=70)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = ['conference', 'name']

class Event(models.Model):
    guid = models.CharField(max_length=36, unique=True)
    conference = models.ForeignKey(Conference)
    title = models.CharField(max_length=255)
    venue = models.ForeignKey(Venue, blank=True, null=True)
    start_date = models.DateTimeField(blank=True)
    end_date = models.DateTimeField(blank=True)
    period = models.ForeignKey(Period, blank=True, null=True,
            help_text="If set, will override start and end dates.")

    description = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if not self.guid:
            self.guid = str(uuid.uuid4())
        if self.period:
            self.start_date = self.period.start_date
            self.end_date = self.period.end_date
        super(Event, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

class RoleType(models.Model):
    conference = models.ForeignKey(Conference)
    role = models.CharField(max_length=70)

    def __unicode__(self):
        return self.role

    class Meta:
        ordering = ['role']

class EventRole(models.Model):
    event = models.ForeignKey(Event)
    role = models.ForeignKey(RoleType, blank=True, null=True)
    person = models.ForeignKey(Person, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.role)

    class Meta:
        ordering = ['role']

class RolePreference(models.Model):
    person = models.ForeignKey(Person)
    roletype = models.ForeignKey(RoleType)

    def __unicode__(self):
        return "{} => {}".format(self.person, self.roletype)

schedule/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from schedule.models import *

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name']

class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Person
        exclude = ['conference']

OtherCommitmentFormset = inlineformset_factory(Person,
        OtherCommitment,
        extra=2,
        fields=['start_date', 'end_date'])

class ProspectiveAdminField(forms.ModelMultipleChoiceField):
    def clean(self, value):
        if not value:
            return self.queryset.none()
        if not isinstance(value, (list, tuple)):
            raise ValidationError(self.error_messages['list'], code='list')
        models = []
        id_values = []
        for val in value:
            if "@" in val:
                try:
                    model, created = self.queryset.get_or_create(email=val)
                except ValueError:
                    return ValidationError(
                            "Invalid email address",
                            code='invalid_email',
                            params={"pk": val})
                models.append(model)
            else:
                try:
                    self.queryset.filter(pk=val)
                except ValueError:
                    raise ValidationError(
                        self.error_messages['invalid_pk_value'],
                        code='invalid_pk_value',
                        params={'pk': val},
                    )
                id_values.append(val)
        qs = list(self.queryset.filter(pk__in=id_values))
        pks = set(str(o.pk) for o in qs)
        for val in id_values:
            if str(val) not in pks:
                raise ValidationError(
                    self.error_messages['invalid_choice'],
                    code='invalid_choice',
                    params={'value': val},
                )
        self.run_validators(value)
        return qs + models

class CreateConferenceForm(forms.ModelForm):
    admins = forms.ModelMultipleChoiceField(User.objects.all(),
            widget=forms.MultipleHiddenInput)
    prospective_admins = ProspectiveAdminField(ProspectiveAdmin.objects.all(),
            widget=forms.MultipleHiddenInput)

    class Meta:
        model = Conference
        fields = ['name', 'public', 'admins', 'prospective_admins']

class UpdateConferenceForm(CreateConferenceForm):
    class Meta(CreateConferenceForm.Meta):
        fields = ['name', 'public', 'admins', 'prospective_admins', 'archived']

class VenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = ['name']

class RoleTypeForm(forms.ModelForm):
    class Meta:
        model = RoleType
        fields = ['role']

class EventForm(forms.ModelForm):
    add_period = forms.BooleanField(required=False,
        label="Add new period",
        help_text='Add these start and end dates as a new "period" (e.g. a course block, track, etc)?')
    period_name = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance', None)
        if instance is None:
            self.fields['period'].queryset = Period.objects.none()
        else:
            self.fields['period'].queryset = instance.conference.period_set.all()

    def clean_period_name(self):
        if self.cleaned_data['add_period'] and not self.cleaned_data.get('period_name'):
            raise ValidationError("Period name is required to add a period.")
        if Period.objects.filter(period=self.cleaned_data['period_name'], 
                conference=self.instance.conference).exists():
            raise ValidationError("That name is already in use.")
        return self.cleaned_data['period_name']

    def clean(self):
        data = super(EventForm, self).clean()
        if not (data['start_date'] or data['period']):
            raise ValidationError("One of start date or period is required.")
        return data

    def save(self):
        event = super(EventForm, self).save(commit=False)
        if self.cleaned_data['add_period']:
            event.period = Period.objects.create(
                conference=self.instance.conference, 
                period=self.cleaned_data['period_name'],
                start_date=event.start_date,
                end_date=event.end_date)
        event.save()
        return event

    class Meta:
        model = Event
        fields = ['title', 'start_date', 'end_date', 'period', 'description']

templates/schedule/_conference_nav.html
{% extends "_main_nav.html" %}

{% block brand %}
<a class="navbar-brand" href="/"><i class='glyphicon glyphicon-home'></i><span class='sr-only'>Home</span></a>
<a class="navbar-brand" href="{{ conference.get_absolute_url }}">{{ conference }}</a>
{% endblock %}

{% block navlinks %}
  {% if is_admin %}
    <li><a href="{% url "conference_update" conference.random_slug %}"><i class='glyphicon glyphicon-cog'></i><span class='sr-only'>Edit conference</span></a></li>
    <li><a href='{% url "event_assigner" conference.random_slug %}'>Event assigner</a></li>
  {% endif %}
  <li><a href='{% url "person_crud" conference.random_slug %}'>People</a></li>
  <li><a href='{% url "venue_crud" conference.random_slug %}'>Venues</a></li>
  <li><a href='{% url "roletype_crud" conference.random_slug %}'>Role Types</a></li>
  <li><a href='{% url "airport_list" conference.random_slug %}'>Airport</a></li>
{% endblock %}

templates/schedule/_event_role_row.html
<tr class='event-role-row' data-event-id='{{ event.pk }}'>
  <td class='date'>
    {% if event.period %}
      <span class='label label-default' data-toggle='tooltip'
        title='{{ event.start_date|date:"D "}}{{ event.start_date|date:"fA"|lower}}&ndash;{{ event.end_date|date:"fA"|lower}}'>{{event.period}}</span>
    {% else %}
      {{ event.start_date|date:"D "}}{{ event.start_date|date:"fA"|lower}}&ndash;{{ event.end_date|date:"fA"|lower}}
    {% endif %}
  </td>
  <td class='title'>{{ event.title }} <a class='btn btn-xs' href='{% url "edit_event" conference.random_slug %}?id={{ event.pk }}'>Edit</a></td>
  <td class='roles'>
      <a class='btn btn-default btn-xs add-event-role'
        href='#' data-event-id='{{ event.pk }}'>
         Add Role
       </a>
    <ul class='event-roles'>
    {% for role in event.eventrole_set.all %}
      <li>
      <a class='remove-event-role' href='{% url "event_role_crud" %}'
         data-event-role-id='{{ role.id }}'>
          <i class='glyphicon glyphicon-trash'></i>
        </a>
        <span class='role-name'>{{ role.role }}</span>
        <span class='role-assignment'>
          {% if role.person %}
            <a href='{% url "personal_schedule" conference.random_slug role.person_id %}'>{{ role.person }}</a>
          {% endif %}
          <a class='edit-event-role' href='#'
              data-event-id='{{ event.id }}'
              data-event-role-id='{{ role.id }}'
              data-roletype-id='{{ role.role.id }}'
              data-person-id='{{ role.person.id }}'>
            {% if not role.person %}&lt;assign&gt;{% endif %}
            <i class='glyphicon glyphicon-pencil'></i>
          </a>
        </span>
    {% endfor %}
    </ul>
  </td>
  <td class='venue'>
    <nobr>
      <input type='text' value='{{ event.venue.id }}' name='venue_id'
             data-url='{% url "get_available_venues" %}'
             data-update-url='{% url "update_event_attribute" %}'
             data-event-id='{{ event.id }}'
             data-venue-name='{{ event.venue.name }}'/>
      {% if is_admin %}
        <a href='{% url "venue_crud" conference.random_slug %}' title='Add venue' data-toggle='tooltip'><i class='glyphicon glyphicon-plus-sign'></i></a>
      {% endif %}
    </nobr>
  </td>
</tr>

templates/schedule/_flat_event_list.html
{% for event in events %}
  {% ifchanged event.start_date|date:"Ymd" %}
  <h2>{{ event.start_date|date:"l N j" }}</h2>
  {% endifchanged %}
  <div class='event'>
    <h3>{{ event.title }}{% if event.venue %} &ndash; {{ event.venue }}{% endif %}</h3>
    <div class='date'>
      {{ event.start_date|date:"f" }}&ndash;{{ event.end_date|date:"fA"}}
      {% if event.period %}
      <small>({{ event.period }})</small>
      {% endif %}
    </div>
    {% if event.eventrole_set.all %}
      <ul>
        {% for eventrole in event.eventrole_set.all %}{% spaceless %}
            {% ifchanged eventrole.role %}
              {% if forloop.counter0 > 0 %}</li>{% endif %}
              <li><i>{{ eventrole.role }}</i>:
            {% else %},{% endifchanged %}
          {% if eventrole.person %}
            {{ eventrole.person }}
          {% else %}
            unassigned
          {% endif %}
        {% endspaceless %}{% endfor %}
        </li>
      </ul>
    {% endif %}
  </div>
{% endfor %}

templates/schedule/airport_list.html
{% extends "base.html" %}

{% block title %}Airport List | {{ conference }}{% endblock %}

{% block main %}
<div class='container'>
  <h2>{{ conference }} Airport Desires</h2>
  <h3>Pickups</h3>
  <ul>
  {% for person in object_list %}
    {% if person.want_airport_pickup %}
    <li>
    <b>{{ person }}</b>
      {% if person.airport_pickup_date %}
        <small>(pick up: {{ person.airport_pickup_date|date:"D fA" }}</small>
      {% elif person.availability_start_date %}
        <small>(no pick up date given &ndash; availability start: {{ person.availability_start_date|date:"D fA" }})</small>
      {% endif %}
      <div style='white-space: pre-wrap'>{{ person.airport_pickup_details }}</div>
    </li>
    {% endif %}
  {% empty %}
    <li>None requested</li>
  {% endfor %}
  </ul>
  <h3>Dropoffs</h3>
  <ul>
  {% for person in object_list %}
    {% if person.want_airport_dropoff %}
    <li>
      <b>{{ person }}</b>
      {% if person.airport_dropoff_date %}
        <small>(pick up: {{ person.airport_dropoff_date|date:"D fA" }}</small>
      {% elif person.availability_end_date %}
        <small>(no drop off date given &ndash; availability end: {{ person.availability_end_date|date:"D fA" }})</small>
      {% endif %}

      <div style='white-space: pre-wrap'>{{ person.airport_dropoff_details }}</div>
    </li>
    {% endif %}
  {% empty %}
    <li>None requested</li>
  {% endfor %}
  </ul>
</div>
{% endblock %}

templates/schedule/conference_list.html
{% extends "base.html" %}
{% block title %}Conferences{% endblock %}
{% block content %}
  <h1>Master Schedule</h1>
  <p>
  Easily create schedules for your next conference. 
  </p>

  <ul>
    <li>Survey volunteer/staff availability and preferences</li>
    <li>Build a schedule of events</li>
    <li>Assign roles, considering availability and preferences</li>
    <li>Assign rooms/venues</li>
    <li>Build personal schedules. Integrates with iCal and printers.</li>
    <li>Participants don't have to create accounts</li>
    <li>Coordinate airport pickups and dropoffs</li>
  </ul>
  <p>
  {% if user.is_authenticated %}
    <a href='{% url "conference_create" %}' class='btn btn-primary'>Create a New Master Schedule</a>
  {% else %}
    Log in or register to create your first conference schedule. It's free.
    <a class='btn btn-primary' href='{% url "registration_register" %}'>Register</a> or <a href='{% url "auth_login" %}'>log in</a>
  {% endif %}
  <h2>Latest master schedules</h2>
  <ul>
    {% for conference in object_list %}
      <li><a href='{{ conference.get_absolute_url }}'>{{ conference }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/schedule/edit_event.html
{% extends "base.html" %}
{% block title %}
  {% if event.id %}Edit "{{ event }}" {% else %}Add Event{% endif %}
{% endblock %}

{% block content %}
<div class='col-md-6'>
  <div class='col-sm-offset-4'>
    <h1>{% if event.id %}Edit &ldquo;{{ event }}&rdquo;{% else %}Add Event{% endif %}</h1>
  </div>
  <form method='post' action='' class='form-horizontal'>{% csrf_token %}
    {% include "_bootstrap_form_horizontal_non_field_errors.html" %}
    {% include "_bootstrap_form_horizontal_field.html" with field=form.title %}
    <div class='date-elements'>
      {% include "_bootstrap_form_horizontal_field.html" with field=form.start_date %}
      {% include "_bootstrap_form_horizontal_field.html" with field=form.end_date %}
    </div>
    {% include "_bootstrap_form_horizontal_field.html" with field=form.period %}

    <div class='add-period-elements'>
      {% include "_bootstrap_form_horizontal_field.html" with field=form.add_period %}
      <div class='period-name-elements'>
        {% include "_bootstrap_form_horizontal_field.html" with field=form.period_name %}
      </diV>
    </div>

    {% include "_bootstrap_form_horizontal_field.html" with field=form.description %}
    <div class='col-sm-4'>
      {% if event.id %}
        <button type='submit' class='btn btn-danger' name='delete' value='1'>
          Delete event
        </button>
      {% endif %}
    </div>
    <div class='col-sm-8'>
      <button type='submit' class='btn btn-primary' name='save' value='1'>
        Save event
      </button>
      <button type='submit' class='btn btn-default' name='add_another' value='1'>
        Save and add another
      </button>
    </div>
  </form>
</div>
<div class='col-md-6'>
  <div class='alert alert-warning'>
    <h2>Tips</h2>
    <ul>
      <li><b>Events</b> are moments in time and space that need to go on a schedule &ndash; including courses, sessions, plenaries, meals, etc.  In the <a href='{% url "event_assigner" conference.random_slug %}'>event assigner</a>, you can assign <b>roles</b> and <b>venues</b> to events.
      <li><b>Periods</b> are blocks of time that are shared by many events &ndash; like a "course block".  Use them as a shortcut to get the same start and end dates for several events.</li>
      <li><b>Roles</b> are volunteer or staff assignments like "Presenter", "A/V support", "Cleanup", etc.  Use roles in the <a href='{% url "event_assigner" conference.random_slug %}'>event assigner</a> to ask people to show up at a particular place and time.
      <li><b>Venues</b> are where events happen &ndash; like rooms, buildings, or addresses. <a href='{% url "venue_crud" conference.random_slug %}'>Edit venues</a>.
    </ul>
  </div>
</div>
<div style='clear: both; margin-bottom: 2em;'></div>

{% endblock %}
{% block js %}
<script type='text/javascript'>
  $("#id_period").on("change", function() {
    $(".add-period-elements").toggle($("#id_period").val() === "");
  }).change();
  $("#id_add_period").on("change", function() {
    $(".period-name-elements").toggle($("#id_add_period").is(":checked"));
  }).change();
  $("#id_period").on("change", function() {
    $(".date-elements").toggle($("#id_period").val() === "");
  }).change();
</script>
{% endblock %}

templates/schedule/master_schedule.html
{% extends "base.html" %}
{% load firstof from future %}
{% load schedule_tags %}
{% block title %}{% firstof filter "Master Schedule" %} | {{ conference }}{% endblock %}

{% block main %}

{% if not chunks %}
  <div class='container'>
    <div class='col-sm-6 col-sm-offset-3'>
      {% if is_admin %}
        {% if not conference.person_set.exists %}
          <div class='alert alert-info'>
            Master Schedule created!
          </div>
        {% endif %}
        <p><b>How this works</b>:
        <ol>
          <li>Add volunteers and staff to the <a href='{% url "person_crud" conference.random_slug %}'>list of people</a> attending your event.  From there, you can find personalized links for surveys for each person, so that they can tell you about their availability during the conference.</li>
          <li>Next, <a href='{% url "edit_event" conference.random_slug %}'>add events</a> to the schedule.</li>
          <li>Finally, assign roles and venues to the events with the <a href='{% url "event_assigner" conference.random_slug %}'>event assigner</a>. This will build the personalized schedule for each person, as well as the master schedule here.</li>
        </ol>
        {% if conference.person_set.exists %}
          Next: <a class='btn btn-primary' href='{% url "edit_event" conference.random_slug %}'>Add Events</a>
        {% else %}
          First step: <a class='btn btn-primary' href='{% url "person_crud" conference.random_slug %}'>Add People</a>
        {% endif %}
      {% else %}
        The schedule will show up here when the admins have created it.
      {% endif %}
    </div>
  </div>
{% else %}
<div class='ms-page'>
  <h1>{% firstof filter "Master Schedule" %} <small><a href='?flat'>Flat view for printing</a></small> <a href='?ical'><img src='{{ STATIC_URL }}img/ical.gif' alt='ical format' /></a></h1>

  <div class='ms'>
    {% for chunk in chunks %}
      <div class='chunk'
          data-start-time='{{ chunk.start|timestamp }}'
          data-end-time='{{ chunk.end|timestamp }}'>

        <div class='timeheader'>
          <div class='timeseries header day'>
            {% for start,end,label in chunk|chunk_days %}
              <div class='day-block'
                  data-start-time='{{ start|timestamp }}'
                  data-end-time='{{ end|timestamp }}'>
                <div class='ms-label'>{{ label }}</div>
              </div>
            {% endfor %}
          </div>
          <div class='timeseries header hour'>
            {% for start,end,label in chunk|chunk_hours %}
              <div class='hour-block'
                  data-start-time='{{ start|timestamp }}'
                  data-end-time='{{ end|timestamp }}'>
                <div class='ms-label'>{{ label }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class='timeseries periods'>
          {% for object in chunk.periods %}
            <div class='time-block'
                 data-start-time='{{ object.start_date|timestamp }}'
                 data-end-time='{{ object.end_date|timestamp }}'>
               <div class='ms-label'>{{ object.period }}</div>
             </div>
          {% endfor %}
        </div>
        <div class='timeseries events'>
          {% for object in chunk.events %}
            <div class='time-block'
                data-event-id='{{ object.id }}'
                data-type='{{ object.type }}'
                data-start-time='{{ object.start_date|timestamp }}'
                data-end-time='{{ object.end_date|timestamp }}'>
              <div class='ms-label'>{{ object.title }}</div>
              {% if object.venue %}
                <b><a href='{% url "venue_schedule" object.venue.random_slug %}'>{{ object.venue }}</a></b>
              {% endif %}
              <span class='date'>
                {{ object.start_date|date:"f" }}&ndash;{{ object.end_date|date:"fA" }}
              </span>
              {% if object.eventrole_set.all %}
                <ul>
                  {% for eventrole in object.eventrole_set.all %}{% spaceless %}
                    {% ifchanged eventrole.role %}
                      {% if forloop.counter0 > 0 %}</li>{% endif %}
                      <li><i>{{ eventrole.role }}</i>:
                    {% else %},{% endifchanged %}
                    {% if eventrole.person %}
                      <a href='{% url "personal_schedule" conference.random_slug eventrole.person.pk %}'>{{ eventrole.person }}</a>
                    {% else %}
                      unassigned
                    {% endif %}
                  {% endspaceless %}{% endfor %}
                  </li>
                </ul>
              {% endif %}
              
            </div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
    <div style='clear: both;'></div>
  </div>
</div>
{% endif %}
  
{% endblock %}

{% block js %}
  <script type='text/javascript' src='{{ STATIC_URL }}js/masterschedule.js'></script>
{% endblock %}